#version 460

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding=0) buffer sampleData
{
	float samples[];
};

layout(std430, binding=1) buffer frequencyData
{
	float frequencies[];
};

layout(rgba32f, binding=2) uniform image2D spectrogramTex;
layout(rgba32f, binding=3) uniform image2D shiftedSpectrogramTexture;

uniform int u_time;
uniform int u_width;
uniform int u_height;
uniform int u_frame; // framecount until u_frame = u_width

// last column is empty: write frequency data to last column
// last column is filled: shift all columns to the left, write frequency data to last column

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    if (texelCoord.x >= u_width || texelCoord.y >= u_height) {
        return;
    }

    vec4 col = vec4(0.,0.,0., 1.);

    if ((u_frame >= u_width) && (texelCoord.x > 0)) {
        //shift left
        ivec2 shiftedCoord = ivec2(texelCoord.x - 1, texelCoord.y);
        col = imageLoad(spectrogramTex, texelCoord);
        imageStore(shiftedSpectrogramTexture, shiftedCoord, col);
    }
    col = vec4(0.05,0.05,0.01, 1.);
    // Write frequency data: to current frame during fill phase, to last column during scroll phase
    int writeColumn = (u_frame >= u_width) ? (u_width - 1) : u_frame;
    if (texelCoord.x == writeColumn) {
        float s = float(frequencies.length() / 2.0 - 1) / float(u_height);
        int idx = int(s * texelCoord.y);
        float f = frequencies[idx];

        if(f > 0.8 ){
            col.x = 1.0;
        }else if(f > 0.5 ){
            col.z = 0.8;
        }else if(f > 0.1 ){
            col.yz = vec2(0.5);
        }else if(f > 0.05){
            col.y = 0.3;
        }else if(f > 0.02){
            col.y = 0.2;
        }
        imageStore(shiftedSpectrogramTexture, ivec2(writeColumn, texelCoord.y), col);
    }
}